name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source Repo
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'ctj12461/notes'
          platform: 'github'
          path: 'source'

      - name: Clone Destination Repo
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'ctj12461/site-output'
          platform: 'github'
          path: 'dest'
      
      - run: cp -rf ./source/* ./dest/notes

      - name: Deploy
        uses: tech-thinker/push-to-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_PAT_TOKEN }}
        with:
          source-directory: 'dest'
          destination-github-username: 'ctj12461'
          destination-repository-name: 'site-output'
          target-branch: main
